### ISSUE TITLE
Doesn't work with webpack5

### ISSUE THREAD

**Issue by breeswish** [jharris4/html-webpack-tags-plugin#65]
Webpack 5 adds `output.publicPath: 'auto'` [by default](https://github.com/webpack/webpack/pull/11258). This causes HtmlWebpackTagsPlugin produce wrong tags.

**Comment by breeswish** [comment]
Oh sorry, later discovered that my assets are served from a manifest file and the name in the manifest file is already wrong.

**Comment by z639** [comment]
@breeswish Are things working for you in webpack5 ?

I've just migrated and this plugin is giving me issues right now, but if you have it working then it might just be something I'm doing wrong.
